{% set name = "bdsim" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bdsim-{{ version }}.tar.gz
  sha256: a823478bdf79008850c35fef5a915ca8da02bda5dcb991d9a98ec8e08a0205d3

build:
  entry_points:
    - bdedit=bdsim.bdedit:main
    - bdrun=bdsim:bdrun
  noarch: python
  script: echo "${PKG_VERSION}" > RELEASE && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - spatialmath-python
    - ansitable
    - pyqt

test:
  imports:
    - bdsim
  commands:
    - pip check
    - bdedit --help
    - bdrun --help
  requires:
    - pip

about:
  home: https://github.com/petercorke/bdsim
  summary: Simulate dynamic systems expressed in block diagram form using Python.
  dev_url: https://github.com/petercorke/bdsim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
