{% set name = "bdsim" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/bdsim-{{ version }}.tar.gz
  sha256: 4b97c47576930dc98a77b0ddbd0476131e1957219a71098c4f0795aa327e8456

build:
  entry_points:
    - bdedit=bdedit.bdedit:main
    - bdrun=bdsim.bin.bdrun:bdrun
    - bdtex2icon=bdsim.tex2icon:main
    - bdedit-app=bdedit.make_app:make_app
    - bdedit-associate-windows=bdedit.associate_bd_windows:main
  noarch: python
  script: echo "${PKG_VERSION}" > RELEASE && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - spatialmath-python
    - ansitable
    - pyqt
    - progress
    - pyside6
    - pillow
    - ipywidgets
    - ipympl

test:
  imports:
    - bdsim
  commands:
    - pip check
    - bdedit --help
    - bdrun --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/petercorke/bdsim
  summary: Simulate dynamic systems expressed in block diagram form using Python.
  dev_url: https://github.com/petercorke/bdsim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
