{% set name = "bdsim" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bdsim-{{ version }}.tar.gz
  sha256: 6502314a977ab975d543c3db1b078e548310f6a8e165bd0badc5be998a170bec
  patches:
    - 10.patch

build:
  entry_points:
    - bdedit=bdsim.bdedit:main
    - bdrun=bdsim:bdrun
  noarch: python
  script: echo "${PKG_VERSION}" > RELEASE && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - spatialmath-python
    - ansitable
    - pyqt

test:
  imports:
    - bdsim
  commands:
    - pip check
    - bdedit --help
    - bdrun --help
  requires:
    - pip

about:
  home: https://github.com/petercorke/bdsim
  summary: Simulate dynamic systems expressed in block diagram form using Python.
  dev_url: https://github.com/petercorke/bdsim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
